In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("Bangladesh-Crime-Dataset.csv")

In [3]:
df.head()

,Unnamed: 0,incident_month,incident_week,incident_weekday,weekend,part_of_the_day,latitude,longitude,incident_place,incident_district,...,literacy_rate,religious_institution,playground,park,police_station,cyber_cafe,school,college,cinema,crime
0,0,7,29,wednesday,0,morning,23.774569,90.355292,adabar,dhaka,...,74.6,4289,99,17,60,478,242,64,40,murder
1,1,1,2,wednesday,0,night,23.774569,90.355292,adabar,dhaka,...,74.6,4289,99,17,60,478,242,64,40,murder
2,2,1,4,tuesday,0,night,23.769808,90.351595,adabor,dhaka,...,74.6,4289,99,17,60,478,242,64,40,murder
3,3,3,9,friday,1,night,23.728907,90.417137,aftabnagar,dhaka,...,74.6,4289,99,17,60,478,242,64,40,murder
4,4,8,34,thursday,0,night,23.847177,90.404133,airport,dhaka,...,74.6,4289,99,17,60,478,242,64,40,murder


In [4]:
df.shape

(6574, 38)

In [5]:
df["weekend"].unique()

array([0, 1])

In [6]:
df.drop("Unnamed: 0", axis=1, inplace=True)

In [12]:
df.head(25)

,incident_month,incident_week,incident_weekday,weekend,part_of_the_day,latitude,longitude,incident_place,incident_district,incident_division,...,literacy_rate,religious_institution,playground,park,police_station,cyber_cafe,school,college,cinema,crime
0,7,29,wednesday,0,morning,23.774569,90.355292,adabar,dhaka,dhaka,...,74.6,4289,99,17,60,478,242,64,40,murder
1,1,2,wednesday,0,night,23.774569,90.355292,adabar,dhaka,dhaka,...,74.6,4289,99,17,60,478,242,64,40,murder
2,1,4,tuesday,0,night,23.769808,90.351595,adabor,dhaka,dhaka,...,74.6,4289,99,17,60,478,242,64,40,murder
3,3,9,friday,1,night,23.728907,90.417137,aftabnagar,dhaka,dhaka,...,74.6,4289,99,17,60,478,242,64,40,murder
4,8,34,thursday,0,night,23.847177,90.404133,airport,dhaka,dhaka,...,74.6,4289,99,17,60,478,242,64,40,murder
5,8,34,thursday,0,night,23.847177,90.404133,airport,dhaka,dhaka,...,74.6,4289,99,17,60,478,242,64,40,murder
6,2,7,sunday,0,night,23.913894,90.320686,ashulia,dhaka,dhaka,...,68.0,1118,78,3,6,16,42,10,3,murder
7,1,1,saturday,1,evening,23.913894,90.320686,ashulia,dhaka,dhaka,...,68.0,1118,78,3,6,16,42,10,3,murder
8,1,2,friday,1,evening,23.913894,90.320686,ashulia,dhaka,dhaka,...,68.0,1118,78,3,6,16,42,10,3,murder
9,2,7,sunday,0,night,23.913894,90.320686,ashulia,dhaka,dhaka,...,68.0,1118,78,3,6,16,42,10,3,murder


In [16]:
df.gender_ration.unique()

array([125, 114, 101,  90, 113,  88, 116,  97,  96, 102,  98,  99, 110,
        94,  89,  86, 109, 107, 108, 100,  93, 103, 105, 104,  95, 117,
        91,  92, 106, 111, 203,  85,  84,  87])

In [14]:
df.precip.unique()

array([6.100e+00, 0.000e+00, 2.190e+01, 6.000e-01, 7.800e+00, 2.600e+00,
       1.030e+01, 2.300e+00, 7.000e+00, 2.100e+00, 1.100e+00, 1.230e+01,
       1.200e+00, 2.800e+01, 7.900e+00, 4.400e+00, 3.570e+01, 1.390e+01,
       2.720e+01, 3.100e+00, 8.000e-01, 3.800e+00, 5.100e+00, 3.400e+00,
       1.700e+00, 3.500e+00, 6.900e+00, 1.000e-01, 4.000e-01, 9.000e-01,
       1.000e+00, 8.200e+00, 7.600e+00, 1.010e+01, 5.040e+01, 1.910e+01,
       1.380e+01, 1.330e+01, 3.650e+01, 8.800e+00, 3.700e+00, 1.580e+01,
       5.500e+00, 7.100e+00, 8.100e+00, 1.800e+00, 4.300e+00, 5.000e+00,
       2.270e+01, 6.300e+00, 2.000e+00, 1.720e+01, 1.130e+01, 1.400e+00,
       1.500e+00, 5.000e-01, 5.900e+00, 9.200e+00, 2.000e-01, 1.570e+01,
       6.000e+00, 2.210e+01, 1.270e+01, 6.200e+00, 1.660e+01, 1.760e+01,
       1.250e+01, 1.000e+01, 1.170e+01, 1.730e+01, 2.500e+00, 7.300e+00,
       7.400e+00, 6.500e+00, 5.700e+00, 1.340e+01, 3.000e+00, 8.000e+01,
       1.140e+01, 2.870e+01, 4.200e+00, 4.510e+01, 

In [13]:
df.incident_month.unique()

array([ 7,  1,  3,  8,  2, 11,  9,  6,  4,  5, 10, 12])

In [8]:
df_copy = df.copy()

In [9]:
df.isna().sum().sum()

np.int64(0)

In [10]:
unique = df["incident_place"].unique()
print(unique)

<StringArray>
[      'adabar',       'adabor',   'aftabnagar',      'airport',
      'ashulia',        'badda',     'bangshal',    'baridhara',
    'bhasantek',      'bhatara',
 ...
    'sreenagar',       'tarail',   'bhedarganj', 'bhurungamari',
       'zajira',   'chitalmari',   'doulatkhan',    'kalukhali',
     'phulbari',     'rajarhat']
Length: 660, dtype: str


In [11]:
for item in unique:
    print(item)

adabar
adabor
aftabnagar
airport
ashulia
badda
bangshal
baridhara
bhasantek
bhatara
banasree
bongshal
bangladesh university of engineering and technology
cantonment
chawkbazar
uttarkhan
dakkhinkhan
darus salam
demra
dhaka university
dhamrai
dhanmondi
domar
donia
gabtoli
gulshan
hazaribagh
hrishikesh das lane
ibrahimpur
islambagh
jatrabari
jurain
kafrul
kalabagan
kalyanpur
kamrangirchar
karail
keraniganj
khilgaon
kuril
lalbagh
malibagh
manda
mirpur
moghbazar
mohakhali
mohammadpur
monipur
mugda
nakhalpara
new market
niketan
old dhaka
pallabi
ramna
rampura
rupnagar
korail
savar
shah ali
shahbagh
shanir akhra
shankaribazar
shekhertek
shewrapara
shyampur
sutrapur
taltola
tejgaon
tikatuli
turag
uttara
vatara
agargaon
aricha highway
banani
bhashantek
dhaka
kalachandpur
madhubagh
sobujbagh
dhaka medical college
manikganj
elephant road
green road
gulistan
jamtala
kadamtali
kakrail
kodomtoli
kurmitola
muslim nagar
sabujbagh
natunbazar
nawabganj
paltan
rayebazar
shantibagh
sher-e-bangla nagar
ton